---
- name: Install Nginx
  dnf:
    name: nginx
    state: present
    
- name: Configure Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/server-inventory.conf
    mode: '0644'
  notify: restart nginx
  
- name: Remove default Nginx config
  file:
    path: /etc/nginx/nginx.conf.default
    state: absent
    
- name: Start and enable Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes