---
- name: Install Nginx
  become_user: root
  remote_user: ansible
  become: true
  dnf:
    name: nginx
    state: present
    
- name: Configure Nginx
  become_user: root
  remote_user: ansible
  become: true
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/server-inventory.conf
    mode: '0644'
  notify: restart nginx
  
- name: Remove default Nginx config
  become_user: root
  remote_user: ansible
  become: true
  file:
    path: /etc/nginx/nginx.conf.default
    state: absent
    
- name: Start and enable Nginx
  become_user: root
  remote_user: ansible
  become: true
  systemd:
    name: nginx
    state: started
    enabled: yes
