---
galaxy_info:
  author: System Administrator
  description: Common system setup for RHEL servers
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 8
        - 9

dependencies: []