---
- name: Update system packages
  become_user: root
  remote_user: ansible
  become: true
  dnf:
    name: "*"
    state: latest
    
- name: Install base packages
  become_user: root
  remote_user: ansible
  become: true
  dnf:
    name:
      - python3
      - python3-pip
#      - python3-venv
      - git
      - firewalld
      - policycoreutils-python-utils
    state: present
    
- name: Create application user
  become_user: root
  remote_user: ansible
  become: true
  user:
    name: "{{ app_user }}"
    system: yes
    shell: /bin/false
    home: "{{ app_dir }}"
    create_home: no
    
- name: Create directories
  become_user: root
  remote_user: ansible
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0755'
  loop:
    - "{{ app_dir }}"
    - "{{ backup_dir }}"
    - "{{ log_dir }}"
    
- name: Configure firewall
  become_user: root
  remote_user: ansible
  become: true
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
    - 5000/tcp
    - 80/tcp
    - 443/tcp
  notify: restart firewalld
  
- name: Configure SELinux
  become_user: root
  remote_user: ansible
  become: true
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
    
#- name: Add SELinux port
  #become_user: root
  #remote_user: ansible
#  become: true
#  community.general.seport:
#  seport:
#    ports: 5000
#    proto: tcp
#    setype: http_port_t
#    state: present
