---
galaxy_info:
  author: System Administrator
  description: Server Inventory Management Application
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 8
        - 9

dependencies:
  - common