---
all:
  children:
    rhel_servers:
      hosts:
        server-inventory-host:
          ansible_host: 192.168.1.4
          ansible_user: ansible
          ansible_become: yes
          ansible_become_method: sudo
      vars:
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
